# Starship documentation
#Â https://starship.rs/config/

# Inserts a blank line between shell prompts
add_newline = false

[cmd_duration]
min_time = 5_000  # Show command duration over 5,000 milliseconds (=5 sec)
format = " took [$duration]($style)"

[git_metrics]
disabled = true
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '
only_nonzero_diffs=true

[git_status]
disabled = true
# Check icons from Nerd Fonts https://www.nerdfonts.com/cheat-sheet
format = "$ahead$behind$staged$conflict$modified$untracked$stashed "
conflicted = "[ó°‡](red)"
ahead = "[î­ ${count}](blue) "
behind = "[ï€™ ${count}](blue) "
untracked = "[î©¿ ${count}](gray) "
stashed = "[ï’‡ ${count}](gray) "
modified = "[ï‘€ ${count}](yellow) "
staged = "[ï¨¦ ${count}](green) "
renamed = "ó°‘•$ {count} "
deleted = "[âœ˜$ {count}](red) "

[git_state]
disabled = true
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[time]
disabled = true
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"

[character]
error_symbol = "[âœ–](bold red) "

[git_branch]
disabled = true

[git_commit]
disabled = true

[hostname]
disabled = true

[battery]
disabled = true

[package]
disabled = true

[username]
disabled = true