# Inserts a blank line between shell prompts
add_newline = false

[git_metrics]
disabled=true

[git_status]
conflicted = "âš”ï¸"
ahead = "â¬†ï¸ ${count}"
behind = "â¬‡ï¸ ${count}"
untracked = "â€ğŸ¤·${count}"
stashed = "ğŸ“¦"
modified = "ğŸ“${count}"
staged = 'â­ï¸${count}'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘ ${count}"

[time]
time_format = "%T"
format = "ğŸ•™ $time($style) "
style = "bright-white"
disabled = false

[character]
error_symbol = "[âœ–](bold red) "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[hostname]
ssh_only = true
format =  "on [$hostname](bold red) "